import { jsPDF } from "jspdf"

export type ReportData = {
  weekNumber: number
  weekStart: string
  weekEnd: string
  name: string
  stats: {
    bible: number
    workout: number
    diet: number
    read: number
    job: number
    runs: number
    daysLogged: number
    totalDays: number
    consistency: number
    startWeight: number | null
    endWeight: number | null
    weightDelta: number | null
  }
  appsThisWeek: number
  totalApps: number
  review: {
    wins?: string | null
    struggles?: string | null
    lessons?: string | null
    nextWeekFocus?: string | null
    rating?: number | null
  }
}

const AMBER: [number, number, number] = [196, 142, 56]
const DARK: [number, number, number] = [42, 38, 34]
const GRAY: [number, number, number] = [110, 110, 110]

export function generateWeeklyReport(data: ReportData) {
  const doc = new jsPDF({ unit: "pt", format: "a4" })
  const pageW = doc.internal.pageSize.getWidth()
  const margin = 48
  let y = 56

  // Header band
  doc.setFillColor(...DARK)
  doc.rect(0, 0, pageW, 96, "F")
  doc.setTextColor(...AMBER)
  doc.setFont("helvetica", "bold")
  doc.setFontSize(22)
  doc.text("The 40-Day Lock In", margin, 50)
  doc.setTextColor(255, 255, 255)
  doc.setFont("helvetica", "normal")
  doc.setFontSize(12)
  doc.text(`Week ${data.weekNumber} Report`, margin, 72)
  doc.setTextColor(200, 200, 200)
  doc.setFontSize(10)
  doc.text(`${data.weekStart}  to  ${data.weekEnd}   ·   ${data.name}`, margin, 88)

  y = 130

  // Section: Discipline scorecard
  sectionTitle(doc, "Discipline scorecard", margin, y)
  y += 22

  const t = data.stats.totalDays
  const rows: [string, string][] = [
    ["Bible + Prayer", `${data.stats.bible} / ${t} days`],
    ["Bodyweight workout", `${data.stats.workout} / ${t} days`],
    ["Diet on track", `${data.stats.diet} / ${t} days`],
    ["Read before sleep", `${data.stats.read} / ${t} days`],
    ["Job action", `${data.stats.job} / ${t} days`],
    ["Runs this week", `${data.stats.runs} (target 2)`],
    ["Overall consistency", `${data.stats.consistency}%`],
  ]
  doc.setFontSize(11)
  for (const [k, v] of rows) {
    doc.setTextColor(...GRAY)
    doc.setFont("helvetica", "normal")
    doc.text(k, margin, y)
    doc.setTextColor(...DARK)
    doc.setFont("helvetica", "bold")
    doc.text(v, pageW - margin, y, { align: "right" })
    y += 18
  }

  y += 14

  // Section: Body + Career
  sectionTitle(doc, "Body & career", margin, y)
  y += 22
  const sw = data.stats.startWeight
  const ew = data.stats.endWeight
  const delta = data.stats.weightDelta
  const bodyRows: [string, string][] = [
    ["Weight (start of week)", sw != null ? `${sw} kg` : "not logged"],
    ["Weight (end of week)", ew != null ? `${ew} kg` : "not logged"],
    ["Change this week", delta != null ? `${delta > 0 ? "+" : ""}${delta} kg` : "—"],
    ["Applications this week", `${data.appsThisWeek}`],
    ["Applications total", `${data.totalApps} / 40`],
  ]
  doc.setFontSize(11)
  for (const [k, v] of bodyRows) {
    doc.setTextColor(...GRAY)
    doc.setFont("helvetica", "normal")
    doc.text(k, margin, y)
    doc.setTextColor(...DARK)
    doc.setFont("helvetica", "bold")
    doc.text(v, pageW - margin, y, { align: "right" })
    y += 18
  }

  y += 14

  // Section: Reflection
  sectionTitle(doc, "Reflection", margin, y)
  y += 22
  if (data.review.rating != null) {
    doc.setTextColor(...GRAY)
    doc.setFont("helvetica", "normal")
    doc.setFontSize(11)
    doc.text("Self rating", margin, y)
    doc.setTextColor(...DARK)
    doc.setFont("helvetica", "bold")
    doc.text(`${data.review.rating} / 10`, pageW - margin, y, { align: "right" })
    y += 24
  }

  y = textBlock(doc, "Wins", data.review.wins, margin, y, pageW)
  y = textBlock(doc, "Struggles", data.review.struggles, margin, y, pageW)
  y = textBlock(doc, "Lessons", data.review.lessons, margin, y, pageW)
  y = textBlock(doc, "Focus for next week", data.review.nextWeekFocus, margin, y, pageW)

  // Footer
  doc.setTextColor(...GRAY)
  doc.setFontSize(9)
  doc.text(
    "Generated by The 40-Day Lock In  ·  Keep showing up.",
    margin,
    doc.internal.pageSize.getHeight() - 32,
  )

  doc.save(`lock-in-week-${data.weekNumber}.pdf`)
}

function sectionTitle(doc: jsPDF, title: string, x: number, y: number) {
  doc.setDrawColor(...AMBER)
  doc.setLineWidth(2)
  doc.line(x, y - 12, x + 24, y - 12)
  doc.setTextColor(...DARK)
  doc.setFont("helvetica", "bold")
  doc.setFontSize(14)
  doc.text(title, x, y)
}

function textBlock(doc: jsPDF, label: string, value: string | null | undefined, x: number, y: number, pageW: number) {
  const margin = x
  let yy = y
  if (yy > doc.internal.pageSize.getHeight() - 100) {
    doc.addPage()
    yy = 56
  }
  doc.setTextColor(...AMBER)
  doc.setFont("helvetica", "bold")
  doc.setFontSize(11)
  doc.text(label, margin, yy)
  yy += 16
  doc.setTextColor(...DARK)
  doc.setFont("helvetica", "normal")
  doc.setFontSize(10)
  const text = value?.trim() || "—"
  const lines = doc.splitTextToSize(text, pageW - margin * 2)
  doc.text(lines, margin, yy)
  yy += lines.length * 14 + 12
  return yy
}
